name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: unzip AsemAinala_source.zip
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.1.1'
      - run: cd AsemAinala && gradle wrapper --gradle-version 8.1.1
      - run: sed -i 's/compileSdk 34/compileSdk 33/g' AsemAinala/app/build.gradle
      - run: sed -i 's/targetSdk 34/targetSdk 33/g' AsemAinala/app/build.gradle
      - run: cd AsemAinala && chmod +x gradlew && ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: AsemAinala/app/build/outputs/apk/debug/app-debug.apk
